#!/usr/bin/env sh
######################################################################
#
# Copyright (c) 2017 Mathieu Kerjouan <contact@steepath.eu>
#
# Permission to  use, copy, modify,  and distribute this  software for
# any purpose with or without fee is hereby granted, provided that the
# above  copyright notice  and this  permission notice  appear in  all
# copies.
#
# THE  SOFTWARE IS  PROVIDED  "AS  IS" AND  THE  AUTHOR DISCLAIMS  ALL
# WARRANTIES  WITH  REGARD  TO  THIS SOFTWARE  INCLUDING  ALL  IMPLIED
# WARRANTIES OF  MERCHANTABILITY AND  FITNESS. IN  NO EVENT  SHALL THE
# AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
# DAMAGES OR ANY  DAMAGES WHATSOEVER RESULTING FROM LOSS  OF USE, DATA
# OR PROFITS,  WHETHER IN AN  ACTION OF CONTRACT, NEGLIGENCE  OR OTHER
# TORTIOUS ACTION,  ARISING OUT OF  OR IN  CONNECTION WITH THE  USE OR
# PERFORMANCE OF THIS SOFTWARE.
#
######################################################################

_date() {
  _exec date | _print_pre
}

_uname() {
  _exec uname -a | _print_pre
}

_dmesg() {
  _exec cat /var/run/dmesg.boot | _print_pre
}

_pci() {
  _exec pciconf -lv | _print_pre
}

_usb() {
  _exec usbconfig | _print_pre
}

_acpi() {
  _exec _apm | _print_pre
}

_netif() {
  _exec ifconfig -a | _print_pre
}

_sysctl() {
  _exec sysctl -a | _print_pre
}

_output() {
  echo wip | _print_pre
}

_input() {
  echo wip | _print_pre
}
