#!/usr/bin/env sh
######################################################################
#
# Copyright (c) 2017 Mathieu Kerjouan <contact@steepath.eu>
#
# Permission to  use, copy, modify,  and distribute this  software for
# any purpose with or without fee is hereby granted, provided that the
# above  copyright notice  and this  permission notice  appear in  all
# copies.
#
# THE  SOFTWARE IS  PROVIDED  "AS  IS" AND  THE  AUTHOR DISCLAIMS  ALL
# WARRANTIES  WITH  REGARD  TO  THIS SOFTWARE  INCLUDING  ALL  IMPLIED
# WARRANTIES OF  MERCHANTABILITY AND  FITNESS. IN  NO EVENT  SHALL THE
# AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
# DAMAGES OR ANY  DAMAGES WHATSOEVER RESULTING FROM LOSS  OF USE, DATA
# OR PROFITS,  WHETHER IN AN  ACTION OF CONTRACT, NEGLIGENCE  OR OTHER
# TORTIOUS ACTION,  ARISING OUT OF  OR IN  CONNECTION WITH THE  USE OR
# PERFORMANCE OF THIS SOFTWARE.
#
######################################################################

_date() {
  date | _print_pre
}

_uname() {
  uname -a | _print_pre
}

_dmesg() {
  cat /var/run/dmesg.boot | _print_pre
}

_pci() {
  local pci line
  for pci in /dev/pci*
  do
    pcictl ${pci} list | while read line
    do
      local id bus device
      id=$(echo ${line} | cut -d: -f0)
      bus=$(echo ${line} | cut -d: -f1)
      device=$(echo ${line} | cut -d: -f2)
      echo "${line}"
      pcictl ${pci} dump -b ${bus} -d ${device} 
    done
  done | _print_pre
}

_usb() {
  usbdevs -dv | _print_pre
}

_acpi() {
  echo wip
}

_netif() {
  ifconfig -a | _print_pre
}

_sysctl() {
  sysctl -a | _print_pre
}

# see wsmuxctl, wsconscfg
_keyboard() {
  wsconsctl -a | _print_pre
}

