#!/usr/bin/env sh
######################################################################
#
# Copyright (c) 2017 Mathieu Kerjouan <contact@steepath.eu>
#
# Permission to  use, copy, modify,  and distribute this  software for
# any purpose with or without fee is hereby granted, provided that the
# above  copyright notice  and this  permission notice  appear in  all
# copies.
#
# THE  SOFTWARE IS  PROVIDED  "AS  IS" AND  THE  AUTHOR DISCLAIMS  ALL
# WARRANTIES  WITH  REGARD  TO  THIS SOFTWARE  INCLUDING  ALL  IMPLIED
# WARRANTIES OF  MERCHANTABILITY AND  FITNESS. IN  NO EVENT  SHALL THE
# AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
# DAMAGES OR ANY  DAMAGES WHATSOEVER RESULTING FROM LOSS  OF USE, DATA
# OR PROFITS,  WHETHER IN AN  ACTION OF CONTRACT, NEGLIGENCE  OR OTHER
# TORTIOUS ACTION,  ARISING OUT OF  OR IN  CONNECTION WITH THE  USE OR
# PERFORMANCE OF THIS SOFTWARE.
#
######################################################################

_date() {
	_print_h1 "Running date:"
	_exec date | _print_pre
}

_uname() {
	_print_h1 "Generic Host information:"
	_exec uname -a | _print_pre
}

_dmesg() {
	_print_h1 "dmesg:"
	_exec cat /var/run/dmesg.boot | _print_pre
}

_pci() {
	_print_h1 "PCI devices:"
	_exec pcidump -v | _print_pre
}

_usb() {
	_print_h1 "USB devices:"
	_exec usbdevs -v | _print_pre
}

_acpi() {
	_print_h1 "ACPI support:"
	_exec apm -v | _print_pre
}

_netif() {
	_print_h1 "available network interfaces:"
	_exec ifconfig -a | _print_pre
}

_sysctl() {
	_print_h1 "system kernel variables:"
	_exec sysctl -a | _print_pre
}

######################################################################
# print output devices information
######################################################################
_output() {
  _display
}

_display() {
  _print_h1 "display configuration:"
  _exec wsconsctl display | _print_pre
}

######################################################################
# print input devices information
######################################################################
_input() {
  _keyboard
  _mouse
}

_keyboard() {
  _print_h1 "keyboard configuration:"
  _exec wsconsctl keyboard | _print_pre
}

_mouse() {
  _print_h1 "mouse configuration:"
  _exec wsconsctl mouse | _print_pre
}

_keyboard() {
	_print_h1 "wscons configuration:"
	_exec wsconsctl -a | _print_pre
}

